spring:
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: h2data
 h2:
  console:
   enabled: true
   settings:
    web-allow-others: true
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  
 database-platform: org.hibernate.dialect.H2Dialect
 
 
 
